---
development:
  dialect: postgres
  database: polar_development
  user: postgres
  password: 0223
  host: 127.0.0.1
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://postgres:0223@127.0.0.1:5432/server_test?sslmode=disable"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://postgres:0223@127.0.0.1:5432/server_production?sslmode=disable"}}
